### PR TITLE
Request error handler on client.js

### PR DESCRIPTION
**Pull request by Kodran**
Hi :)
I was writing a module to send information of my IoT devices to azure, but sometimes the library returns some unhandled exceptions on my requests, something like:

Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at onread (net.js:556:19)

So, I modified a little the file: client.js to catch those exceptions :)

### CODE REVIEW

**Comment by ytechie** [comment]
Thanks!

**Comment by Kodran** [comment]
I wonder if there's any chance to upload this change to npm? otherwise, we can plan a major version :)

**Comment by Kodran** [comment]
I wonder if there's any chance to upload this change to npm? otherwise, we can plan a major version :)

**Comment by ytechie** [comment]
Done. Sorry it took so long.

**Comment by Kodran** [comment]
Cool !! thanks alot @ytechie

**Pull request merged**
